import {
  siTypescript,
  siJavascript,
  siReact,
  siNextdotjs,
  siExpress,
  siSpringboot,
  siTailwindcss,
  siPostgresql,
  siMongodb,
  siFirebase,
  siDocker,
  siPython,
  siPytorch,
  siTensorflow,
  siKeras,
  siScikitlearn,
  siNumpy,
  siPandas,
  siRos,
  type SimpleIcon,
} from "simple-icons";

export const skillIcons: Record<string, SimpleIcon> = {
  TypeScript: siTypescript,
  JavaScript: siJavascript,
  "React.js": siReact,
  "Next.js": siNextdotjs,
  "Express.js": siExpress,
  "Spring Boot": siSpringboot,
  "Tailwind CSS": siTailwindcss,
  PostgreSQL: siPostgresql,
  MongoDB: siMongodb,
  Firebase: siFirebase,
  Docker: siDocker,
  Python: siPython,
  PyTorch: siPytorch,
  TensorFlow: siTensorflow,
  Keras: siKeras,
  "scikit-learn": siScikitlearn,
  NumPy: siNumpy,
  Pandas: siPandas,
  ROS2: siRos,
};
